### ISSUE TITLE
ویرایش کانفیگ

### ISSUE THREAD

**Issue by arshambh** [Ptechgithub/configs#1]
سلام 
من کلودفلر خودم ساختم و uuid تغییر دادم در داخل فایل `peyman-nekobox-gift.json` خیلی جاها نوشته `server_name` و `uuid` و نمیدونم کدوم بخش هارو باید تغییر بدم. میشه راهنمایی کنید؟
سپاس

**Comment by Ptechgithub** [comment]
سلام 5 تا کانفیگ worker داره از 1 تا 5 هر کدوم 2 جا برای دامین worker و یک مورد برای uuid داره میتونی به جای همش فرار بدی یا ببین کدومش کار نمیکنه به جای اون قرار بده فقط یادت نره هر شماره نیاز به تغییر دامنه در بخش host و server_name داره و uuid

**Comment by arshambh** [comment]
تشکر بابت راهنمایی درست شد.
فقط امکانش هست نسخه کامپیوتر هم درست کنید؟

**Comment by csharpfarsi** [comment]
خیلی ممنون از اموزش خوبتون؟
من تونستم بسازم و ببرم روی نکوباکس ولی امکانش هست بتونیم ببریم روی برنامه v2rayng ؟ اگه هست ممنون میشم راهنمایی بفرمایین

روی آیفون چطوری اجراش کنیم؟

**Comment by Ptechgithub** [comment]
روی v2ray نه نمیشه. روی ios هم فایل گذاشتم
