### ISSUE TITLE
درخواست قالب بر اساس سینگ باکس 1.8

### ISSUE THREAD

**Issue by Graveyard9988** [Ptechgithub/configs#2]
درود
از هسته سینگ باکس 1.8 ساختار کانفیگ ها تغییر کرده است. ساختار پیشنهادی زیر قابلیت بای پس کردن دامین ها و آیپی های ایرانی را داراست و همچنینن ترکر ها و تبلیغات و باج افزار ها را بلاک می کند:
https://pastebin.com/raw/JQScLZxi

لطفا طبق ساختار مندرج در لینک فوق، نسبت به ایجاد peyman-nekobox-gift.json جدید (مختص سینگ باکس 1.8 ) اقدام کنید

بابت تمامی زحمات شما سپاسگزارم

**Comment by Ptechgithub** [comment]
سلام ممنون

**Comment by Graveyard9988** [comment]
https://pastebin.com/raw/677dWQnb

ساختار به روزرسانی شده در لینک جدید
